---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: deploy
  become: True
  gather_facts: True

  roles:
    - common
    - mailserver
    - webmail
    - blog
